config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }  
  
  get 'homes/index'
  root to: 'homes#index'
  get 'search', to:'homes#search'
  
  get 'users#index', to: 'users#index'
  
  get 'reservations/index'
  get '/reservations', to:'reservations#index'

  get 'reservations/:id', to: 'reservations#show', as: 'reservations_show'
  post 'reservations/:id', to: 'reservations#create'


  get 'rooms/index'
  get '/rooms', to: 'rooms#index'

  get 'rooms/new'
  post 'rooms/new', to: 'rooms#create'

  get 'rooms/:id', to: 'rooms#show', as: 'room'
  post 'rooms/:id', to: 'reservations#confirm'

  get 'users/index'
  get '/users', to: 'users#index'
  
  get 'users/profile'
  patch 'users/profile', to: 'users#update'
  
  get 'users/account'

  get 'users/rooms', to: 'users#show', as: 'users_show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  
  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true
  validates :introduction, length: { maximum: 200 } 
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'application'
  before_action :authenticate_user!, only: [:profile, :update, :account]
  
  def index
    @msg = 'this is sample page.'
    @rooms = Room.all
  end

  def profile
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "Profile was successfully updated."
      redirect_to action: :profile
    else
      render action: :profile
    end  
  end
  
  def account
    @user = current_user
  end  
  
  def show
    @user = current_user
    @rooms = @user.rooms
  end 
  
  private
  def user_params
    params.require(:user).permit(:image, :name, :introduction)
  end  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div class="row">
  <div class="col-sm-2 side_bar">
  	<%= link_to "アカウント", users_account_path, class:"side_bar_contents" %>
  	<%= link_to "プロフィール", users_profile_path, class:"side_bar_black" %>
  </div>
  <div class="col-sm-10 pages ajust_container">
  	<div class="container input_form_field">
			<div class="input_form">
				<div class="row under_line">
					<h3 class="col-sm-4">アカウント</h3>
				</div>
				<div class="row under_line">
					<div class="col-sm-4">
						<label for="email">メールアドレス</label>
					</div>
					<p class="col-sm-8"><%= @user.email %></p>
				</div>
				<div class="row under_line">
					<div class="col-sm-4">
						<label for="password">パスワード</label>
					</div>
					<p class="col-sm-8">*********</p>
				</div>
        <%= link_to  "編集", edit_user_registration_path, class:"btn btn-primary input_submit col-sm-4" %>
			</div>	
  	</div>
  </div>
</div>	
		
		

app/views/users/index.html.erb
<h1 class="display-4 text-primary">Users#index</h1>
<p><%= @msg %></p>
<hr>
<div>
  <%= link_to 'login_check page!&gt;&gt;'.html_safe,
  {action:'login_check'} %>
</div>
<div>
  <%= link_to "sign out&gt;&gt;".html_safe,
  destroy_user_session_path,
  method: :delete %>
</div>
<div>
  <%= link_to "ルーム登録&gt;&gt;".html_safe, '/rooms/new' %>
</div>

app/views/users/profile.html.erb
<span class="flash_notice"><%= flash[:notice] %></span>
<div class="row profile_container">
  <div class="col-sm-2 side_bar">
  	<%= link_to "アカウント", users_account_path, class:"side_bar_black pages" %>
  	<%= link_to "プロフィール", users_profile_path, class:"side_bar_contents" %>
  </div>
  <div class="col-sm-10 pages">
  	<div class="container input_form_field">
      <%= form_for(@user, url:{controller:'users', action:'update'}) do |form| %>
  			<div class="input_form">
  				<div class="row under_line">
  					<h3 class="col-sm-4">プロフィール</h3>
  				</div>
  				<div class="row under_line">
            <% if current_user.image.attached? %>
              <%= image_tag current_user.image, class:"profile_img" %>
            <% else %> 
              <%= image_tag "https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon.jpg", class:"profile_img" %>
            <% end %>  
  				</div>
  				<div class="row under_line">
  					<div class="col-sm-4">
  						<label for="image">アイコン画像</label>
  						<span class="btn btn-danger btn-sm disabled">必須</span>
  					</div>
  					<%= form.file_field :image, class:"col-sm-8" %>
  				</div>
  				<div class="row under_line">
  					<div class="col-sm-4">
  						<label for="name">名前</label>
  						<span class="btn btn-danger btn-sm disabled">必須</span>
  					</div>
  					<%= form.text_field :name, class:"col-sm-8" %>
  				</div>
  				<div class="row under_line">
  					<div class="col-sm-4">
  						<label for="image">自己紹介</label>
  						<span class="btn btn-danger btn-sm disabled">必須</span>
  					</div>
  					<%= form.text_area :introduction, class:"col-sm-8 input_info" %>
  				</div>
  				<%= form.submit "更新", class:"btn btn-primary input_submit col-sm-4" %>
  			</div>	
      <% end %>  
  	</div>
  </div>
</div>	

app/views/users/show.html.erb
<div class="container pages">
  <h4>登録済みルーム一覧</h4>
  <table class="table table-striped width">
      <thead>
        <tr>
          <th scope="col">ルーム画像</th>
          <th scope="col">ルーム名</th>
          <th class="room_introduction" scope="col">ルーム紹介</th>
          <th scope="col">料金</th>
          <th scope="col">作成日</th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td>
              <%= link_to room_path(room.id) do %>
                <% if room.image.attached? %>
                  <%= image_tag room.image, class:"img" %>
                <% end %>        
              <% end %>  
            </td>
            <td>
              <%= link_to room_path(room.id) do %>
                <p><%= room.room_name%></p>
              <% end %>  
            </td>
            <td class="room_reservation_info">
              <p><%= room.room_introduction %></p>
            </td>
            <td class="room_reservation_info">
              <p>¥<%= room.price %><p>
            </td>
            <td class="room_reservation_info">
              <p><%= room.created_at %><p>
            </td>
          </tr>
        <% end %> 
      </tbody>
  </table>
</div>