config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }  
  
  get 'homes/index'
  root to: 'homes#index'
  get 'search', to:'homes#search'
  
  get 'users#index', to: 'users#index'
  
  get 'reservations/index'
  get '/reservations', to:'reservations#index'

  get 'reservations/:id', to: 'reservations#show', as: 'reservations_show'
  post 'reservations/:id', to: 'reservations#create'


  get 'rooms/index'
  get '/rooms', to: 'rooms#index'

  get 'rooms/new'
  post 'rooms/new', to: 'rooms#create'

  get 'rooms/:id', to: 'rooms#show', as: 'room'
  post 'rooms/:id', to: 'reservations#confirm'

  get 'users/index'
  get '/users', to: 'users#index'
  
  get 'users/profile'
  patch 'users/profile', to: 'users#update'
  
  get 'users/account'

  get 'users/rooms', to: 'users#show', as: 'users_show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :rooms
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room
  
  validates :start_date, presence: true
  validates :finish_date, presence: true
  validates :number_of_people, presence: true
  
  validate :start_end_check
  validate :start_date_before_today

  def start_end_check
    if start_date.present? && finish_date.present? && start_date >= finish_date
      errors.add(:finish, "は開始日以降の日付で選択してください")
    end 
  end
  
  def start_date_before_today
    if start_date.present? && finish_date.present? && start_date < Date.today
      errors.add(:start_date, "は今日以降の日付で選択してください")
    end
  end 
end
 

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations
  has_one_attached :image
  
  validates :room_name, presence: true
  validates :room_introduction, presence: true
  validates :price, presence: true
  validates :adress, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  
  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true
  validates :introduction, length: { maximum: 200 } 
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @account = Account.find(params[:id])
    @rooms = Room.where(person_id: @account.id) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller? 
  before_action :set_search
  
  #deviseの遷移先変更
  
  def after_sign_in_path_for(resource)
    root_path(resource)
  end
  
  def after_sign_up_path_for(resource)
    root_path(resource)
  end
  
  def after_sign_out_path_for(resource)
    root_path(resource)
  end
  
  def after_update_path_for(resource)
    edit_user_registration_path(resource)
  end


  
  private
  def set_search
    @q = Room.ransack(params[:q])
    @results = @q.result
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image, :introduction])
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  layout 'application'
  before_action :authenticate_account!, only: :login_check
  
  def index
    @msg = 'this is sample page.'
  end

  def login_check
    @account = current_account
    @msg = 'account created at: ' + @account.created_at.to_s
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def index
  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :authenticate_user!, only: [:index, :create, :confirm]
  
  def index
    @reservations = Reservation.all
  end
  
  def confirm
    @room = Room.find(params[:id])
    @reservation = Reservation.new(reservation_params)
    @reservation.room = @room
    if @reservation.invalid?
      render template: 'rooms/show'
    else  
      @dates_of_reservation = (@reservation.finish_date - @reservation.start_date).to_i
    end  
  end  
  
  def create
    @room = Room.find(params[:id])
    @reservation = Reservation.new(reservation_params)
    @reservation.room = @room
    if params[:back]
      render template: 'rooms/show'
    elsif @reservation.save
      flash[:notice] = "Reservation was successfully created."
      redirect_to reservations_show_path(@reservation.id)
    else
      render room_path(@reservation.room.id)
    end
  end  

  def show
    @reservation = Reservation.find(params[:id])
    @dates_of_reservation = (@reservation.finish_date - @reservation.start_date).to_i
  end
  
  
  private
  def reservation_params
    params.require(:reservation).permit(:start_date, :finish_date, :number_of_people, :room_id)
  end 
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    if @room.save
      flash[:notice] = "Room was successfully created."
      redirect_to @room
    else
      render 'new'
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end
  
  def search
    @results = @q.result
  end
  
  private
  def room_params
    params.require(:room).permit(:room_name, :room_introduction, :price, :adress, :user_id, :image)
  end
  
  def set_q
    @q = Room.ransack(params[:q])
  end
  
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'application'
  before_action :authenticate_user!, only: [:profile, :update, :account]
  
  def index
    @msg = 'this is sample page.'
    @rooms = Room.all
  end

  def profile
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "Profile was successfully updated."
      redirect_to action: :profile
    else
      render action: :profile
    end  
  end
  
  def account
    @user = current_user
  end  
  
  def show
    @user = current_user
    @rooms = @user.rooms
  end 
  
  private
  def user_params
    params.require(:user).permit(:image, :name, :introduction)
  end  
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoomApp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <header>
      <div class="header_logo">
        <a href="/"><img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png"></a>
      </div>
      <div class="header_search">
        <%= search_form_for @q, url: search_path do |f| %>
          <%= f.search_field :adress_cont, placeholder:"東京" %>
          <%= f.search_field :room_name_or_room_introduction_or_price_or_adress_cont, placeholder:"キーワード",class:"header_input" %>
          <i class="fas fa-map-marker-alt"></i>
          <i class="fas fa-search"></i>
          <%= f.submit '探す',class:"search_btn" %>
        <% end %> 
      </div>
      <div class="header_user">
        <% if user_signed_in? %>
          <span><%= current_user.name %></span>
          <% if current_user.image.attached? %>
            <%= image_tag current_user.image, class:"header_user_img", alt:"プロフィール画像" %>
          <% else %>
              <%= image_tag "https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon.jpg", class:"header_user_img", alt:"プロフィール画像"  %>
          <% end %> 
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class:"btn btn-primary" %>
          <%= link_to "登録する", new_user_registration_path, class:"btn btn-secondary" %>
        <% end %> 
      </div>
    </header>
    <%= render "shared/headernav" %>
    <%= yield %>
    <footer>
      <p>© 2020 POTEPAN.INC.</p>
    </footer>
     <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
     <script>
       'user strict';
       
       $(document).ready(function(){
         $('.header_user_img').on('click', function(){
           $('#nav').toggle();
         });
       });
     </script>
  </body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></p>
    </ul>
  <% end %>
<% end %>

app/views/shared/_headernav.html.erb
<% if user_signed_in? %>
  <nav id ="nav" class="show">
    <ul>
      <li><%= link_to "ルーム登録", rooms_new_path %></li>
      <li><%= link_to "予約済みルーム一覧", reservations_path %></li>
      <li><%= link_to "登録済みルーム一覧", users_show_path(current_user) %></li>
      <li><%= link_to "設定", users_account_path %></li>
      <li><%= link_to " ログアウト", destroy_user_session_path, method: :delete %></li>
    </ul>
  </nav>
<% end %> 